---
- name: "Ensure destination for Compose file exists - {{ directory }}"
  file:
    path: "{{ directory }}"
    state: directory
  vars:
    directory: "{{ docker_compose_generator_output_path }}"

- name: "Write docker-compose file - {{ full_path }}"
  template:
    src: ../templates/docker-compose.yml.j2
    dest: "{{ full_path }}"
    owner: "{{ docker_compose_generator_uid }}"
    group: "{{ docker_compose_generator_gid }}"
  vars:
    full_path: "{{ docker_compose_generator_output_path }}/docker-compose.yml"

